name = input()
cost = int(input())
weight = int(input())
money = int(input())
print("================Чек================")
print(f"Товар:{" " * (29 - len(name)) + name}")
print(f"Цена:{" " * (19 - len(str(weight) + str(cost)))}{weight}кг * {cost}руб/кг")
print(f"Итого:{" " * (26 - len(str(weight * cost)))}{weight * cost}руб")
print(f"Внесено:{" " * (24 - len(str(money)))}{money}руб")
print(f"Сдача:{" " * (26 - len(str(money - weight * cost)))}{money - weight * cost}руб")
print("===================================")